### ISSUE TITLE
Dock.app may not be scriptable, with SIP disabled

### ISSUE THREAD

**Issue by lucaorio** [koekeishiya/chwm-sa#16]
Hello, this may be related to #15 . 

On Mojave 10.14 (18A391):
```
$ csrutil status
System Integrity Protection status: disabled.
```

However, after running `inject` I always get:
```
$ ~/.../chwm-sa/inject_test/bin/inject
process found
2018-11-27 22:04:46.665 inject[3086:29620] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
event sent
```

Any info or help on how to solve this?

**Comment by lucaorio** [comment]
Hi @koekeishiya , sorry to mention you. I was wondering if you had any thought on this. :)

**Comment by dominiklohmann** [comment]
The warning can be safely ignored—I cannot remember a version of chwm-sa not triggering that warning. 

Also chwm-sa is bundled with chunkwm.

```sh
# Instead of manually copying all the files
sudo chunkwm --install-sa

# Instead of running the injector
chunkwm --load-sa
```

Desktop creation/removal only works on 10.14.2 on current HEAD, everything else should work in 10.13+.

**Comment by koekeishiya** [comment]
This warning is just because there is no .sdef file within the Dock.app "folder".
This file is supposed to define an interface for applications that provides an API such that external software written by other people can call functions or otherwise interact with  a running instance of the application. (see e.g Spotify as an example).

The Dock.app provides no such definition, and that is what this warning is about.
It is not related to how we use the Scripting Bridge framework for code injection.

Hopefully this clears up some misconceptions regarding this warning.

For people who are more interested, search up "sdef", "scripting bridge framework", "scriptable applications" on google/apple docs.

**Comment by lucaorio** [comment]
@dominiklohmann @koekeishiya Thank you so much! I just had a bit of time to try this, and it works perfectly! 🙏
